repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: dcochecker 

  # A short description of the repository that will show up on GitHub
  description: ✔️ DCO Checker GitHub Action
  
  homepage: https://cncf.io/projects

  # Collaborators: give specific users access to this repository.
collaborators:
  # Admins
  - username: caniszczyk
    permission: admin

  - username: idvoretskyi
    permission: admin
    
  - username: amye
    permission: admin

